fprintf("\n\n");
fprintf("narrow, %0.1e +- %0.1e, n = %d movies\n", nanmean(data4stats(:, 1)), sem(data4stats(:, 1)), sum(~isnan(data4stats(:, 1))));

crossEnergy_p = nan(6, 1);
[p, h] = ranksum(data4stats(:, 1), data4stats(:, 2));
fprintf("dSF = %0.1e +- %0.1e, n = %d movies, Wilcoxon–Mann–Whitney U test, SF versus narrow, p = %0.1e\n", ...
    nanmean(data4stats(:, 2)) - nanmean(data4stats(:, 1)), ...
    sem(data4stats(:, 2) - nanmean(data4stats(:, 1))), ...
    sum(~isnan(data4stats(:, 1)) + ~isnan(data4stats(:, 2))), 6*p)
crossEnergy_p(1) = 6*p;

[p, h] = ranksum(data4stats(:, 1), data4stats(:, 3));
fprintf("dOri = %0.1e +- %0.1e, n = %d movies, Wilcoxon–Mann–Whitney U test, Ori versus narrow, p = %0.1e\n", ...
    nanmean(data4stats(:, 3)) - nanmean(data4stats(:, 1)), ...
    sem(data4stats(:, 3) - nanmean(data4stats(:, 1))), ...
    sum(~isnan(data4stats(:, 1)) + ~isnan(data4stats(:, 3))), 6*p)
crossEnergy_p(2) = 6*p;

[p, h] = ranksum(data4stats(:, 1), data4stats(:, 4));
fprintf("dmixed = %0.1e +- %0.1e, n = %d movies, Wilcoxon–Mann–Whitney U test, mixed versus narrow, p = %0.1e\n", ...
    nanmean(data4stats(:, 4)) - nanmean(data4stats(:, 1)), ...
    sem(data4stats(:, 4) - nanmean(data4stats(:, 1))), ...
    sum(~isnan(data4stats(:, 1)) + ~isnan(data4stats(:, 4))), 6*p)
crossEnergy_p(3) = 6*p;

fprintf("\n");

a = 2; b = 3; [p, h] = ranksum(data4stats(:, b), data4stats(:, a));
fprintf("Ori - SF = %0.1e +- %0.1e, n = %d movies, Wilcoxon–Mann–Whitney U test, SF versus narrow, p = %0.1e\n", ...
    nanmean(data4stats(:, b)) - nanmean(data4stats(:, a)), ...
    sem(data4stats(:, b) - nanmean(data4stats(:, a))), ...
    sum(~isnan(data4stats(:, b)) + ~isnan(data4stats(:, a))), 6*p)
crossEnergy_p(4) = 6*p;

a = 2; b = 4; [p, h] = ranksum(data4stats(:, b), data4stats(:, a));
fprintf("mixed - SF = %0.1e +- %0.1e, n = %d movies, Wilcoxon–Mann–Whitney U test, SF versus narrow, p = %0.1e\n", ...
    nanmean(data4stats(:, b)) - nanmean(data4stats(:, a)), ...
    sem(data4stats(:, b) - nanmean(data4stats(:, a))), ...
    sum(~isnan(data4stats(:, b)) + ~isnan(data4stats(:, a))), 6*p)
crossEnergy_p(5) = 6*p;

a = 3; b = 4; [p, h] = ranksum(data4stats(:, b), data4stats(:, a));
fprintf("mixed - Ori = %0.1e +- %0.1e, n = %d movies, Wilcoxon–Mann–Whitney U test, SF versus narrow, p = %0.1e\n", ...
    nanmean(data4stats(:, b)) - nanmean(data4stats(:, a)), ...
    sem(data4stats(:, b) - nanmean(data4stats(:, a))), ...
    sum(~isnan(data4stats(:, b)) + ~isnan(data4stats(:, a))), 6*p)
crossEnergy_p(6) = 6*p;

fprintf("\n\n");

